version: '3.8'

services:
  app:
    image: 676768860871.dkr.ecr.ap-south-1.amazonaws.com/node-js-server:latest
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/your-database

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: